version: "2"

services:
  monit:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
    pid: host
    network_mode: host
    ports:
      - 2812:2812
    build: .